AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for sam-smith generated project

Resources:

  BoilerPlateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-BoilerPlateFunction
      CodeUri: src/
      Handler: BoilerPlate.hello
      Runtime: nodejs20.x
      Timeout: 60
      Architectures:
        - x86_64
      Events:
        event1:
          Type: Api
          Properties:
            RestApiId: !Ref BoilerPlateApi
            Path: /hello
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - BoilerPlate.ts
        External:
          - aws-sdk

  BoilerPlateApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-BoilerPlateApi
      StageName: default
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"

  BoilerPlateFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${BoilerPlateFunction}'
      RetentionInDays: 7

Outputs:
  BoilerPlateApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${BoilerPlateApi}.execute-api.${AWS::Region}.amazonaws.com/default"
